#okta:
#  oauth2:
#    client-id: 0oagqzcu86BBOq2jF0h7
#    issuer: https://dev-737523.oktapreview.com/oauth2/default
firebase:
  databaseUrl: https://dev-nexus-2020.firebaseio.com #${FIREBASE_DATABASE}

security:
  alloweddomains: http://localhost:4200
  allowedmethods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowedheaders:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - Cache-Control
  allowedpublicapis:
    - /favicon.ico
    - /public/data